name: mi_intesud_social
description: Red social institucional INTESUD
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 Animaciones suaves y pro
  animations: ^2.0.11

  # 🔥 Google Fonts (opcional pero recomendado)
  google_fonts: ^6.2.1

  # 🔥 Utils responsive
  flutter_screenutil: ^5.9.3

  # (Preparado para Firebase futuro — puedes activarlo luego)
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.1
  # cloud_firestore: ^5.4.4
  # firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 🔥 ASSETS
  assets:
    - assets/images/logo1.png
    - assets/images/Buzosdeportivos.webp
    - assets/images/gorraintesud.webp
    - assets/images/mochilaintesud.webp
    - assets/images/polera.jpg
    - assets/images/tomatodo.jpg
    - assets/images/computadora.webp
    - assets/images/mariagonzales.webp
    - assets/images/intesudoficial.webp
    - assets/images/desarrollodesoftware.png
    - assets/images/cuadernoinstitucional.webp
    - assets/images/pasebusmensual.jpg

  # Si luego agregas más imágenes:
  # - assets/images/